from pathlib import Path

STORAGE_THRESHOLD_PERCENT = 80

MAX_FILE_SIZE_MB = 0.1
LOG_DIRECTORY = Path("logs10")
LOG_DIRECTORY_MAX_SIZE_MB = 0.5
MAX_COMPRESSION_PERCENT = 70
QUEUE_SIZE = 100000

DEFAULT_FILE_TYPE = "csv"
DEFAULT_COMPRESS = False
ENCODER = False


LOG_TIMESTAMP_FORMAT = "%Y%m%d_%H%M%S"